///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test_git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the test_gitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("4d3fa765-c392-4424-a0c5-368368e6d227")]
    public partial class test_gitRepository : RepoGenBaseFolder
    {
        static test_gitRepository instance = new test_gitRepository();

        /// <summary>
        /// Gets the singleton class instance representing the test_gitRepository element repository.
        /// </summary>
        [RepositoryFolder("4d3fa765-c392-4424-a0c5-368368e6d227")]
        public static test_gitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public test_gitRepository() 
            : base("test_gitRepository", "/", null, 0, false, "4d3fa765-c392-4424-a0c5-368368e6d227", ".\\RepositoryImages\\test_gitRepository4d3fa765.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4d3fa765-c392-4424-a0c5-368368e6d227")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class test_gitRepositoryFolders
    {
    }
#pragma warning restore 0436
}